######################################################################
##
## Filename: uart_test_tb.udo
## Created on: Tue May 07 9:22:38 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
