######################################################################
##
## Filename: pll_test_tb.udo
## Created on: Mon May 06 19:30:51 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
