######################################################################
##
## Filename: key_debounce_tb.udo
## Created on: Tue May 07 10:22:11 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
